name: Build and Publish Pipeline

on:
  push:
    branches:
      - main
      - master
      - prod
  pull_request:
    branches:
      - main
      - prod
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore .\azureddns.sln
    
    - name: Build
      run: dotnet build .\azureddns.sln --configuration Release --no-restore

    - name: Test
      run: cd testazureddns && dotnet test --verbosity normal --no-restore

    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.0.1

    - name: Pulumi Up
      if: github.event_name == 'pull_request' && github.base_ref == 'prod'
      run: |
        cd deployment
        pulumi up -yf
      env:
        ARM_USE_MSI: true
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
